version: '3.7'

services:
  lb:
    image: nginx:1.21
    container_name: load-balancer-container
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/certs/eshop-st-web+10.pem:/etc/nginx/certs/app-cert.pem:ro
      - ./nginx/certs/eshop-st-web+10-key.pem:/etc/nginx/certs/app-cert-key.pem:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - base-service
    restart: on-failure
    networks:
      - snyder-apps-network

  web-gateway:
    image: snyder-apps/web-gateway:latest
    container_name: snyder-web-gateway
    build:
      context: ../../
      dockerfile: gateways/web/src/SnyderApps.WebGateway/Dockerfile
    environment:
      # - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    restart: on-failure
    networks: 
      - snyder-apps-network
    ports:
      - "5000:80"

  base-service:
    image: snyder-apps/base-service:latest
    container_name: snyder-base-service
    build:
      context: ../../
      dockerfile: services/base-service/src/SnyderApps.BaseService.Client/Dockerfile
    environment:
      # - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    restart: on-failure
    networks: 
      - snyder-apps-network
    ports:
      - "5001:80"

networks:
  snyder-apps-network:
    external: true
